language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
before_script:
    - DIR=$(pwd)
    - git clone https://github.com/PermutaTriangle/Permuta.git /tmp/Permuta
    - cd /tmp/Permuta
    - make -C exact_cover
    - make -C exact_cover install
    - python setup.py install
    - cd $DIR
script:
    - python setup.py test
