language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
before_script:
    - DIR=$(pwd)
    - git clone https://github.com/PermutaTriangle/Permuta.git /tmp/Permuta
    - cd /tmp/Permuta
    - sudo python2.7 setup.py install
    - sudo python3.2 setup.py install
    - sudo python3.3 setup.py install
    - sudo python3.4 setup.py install
    - cd $DIR
script: python setup.py test
